version: 0.1.0.{build}
os: Visual Studio 2019
environment:
  version: 27
  matrix:
    - TRIPLET: x86-windows-static
    - TRIPLET: x64-windows-static
#    - TRIPLET: x86-uwp
#    - TRIPLET: x64-uwp
#    - TRIPLET: arm-uwp
#    - TRIPLET: arm-windows
#    - TRIPLET: arm64-windows
#    - TRIPLET: arm64-uwp
install:
- cmd: install.bat
build_script:
- cmd: >-
    build.bat

    package.bat
test: off
artifacts:
- path: '**\openrct2*.zip'
  name: Zip simplified archive
- path: '**\vcpkg*.zip'
  name: Zip vcpkg archive
- path: '**\vcpkg*.nupkg'
  name: NuGet vcpkg archive
deploy:
  provider: GitHub
  auth_token:
    secure: uXuMd3cu0eDp/Sz+XPaIVyROW36oLcxY0u72smAOAcn6LSViamfbxf9WpgcxQp1z
  artifact: Zip simplified archive
  draft: true
  on:
    APPVEYOR_REPO_TAG: true
